# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d6989a96f37a9f08b98c8e6819f9efe"
application_url = "https://marc-operation-bidder-vaccine.trycloudflare.com"
embedded = true
name = "Quantity-Breaks-Testing"
handle = "quantity-breaks-testing-1"

[build]
include_config_on_deploy = true
dev_store_url = "bundle-app-v5.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://marc-operation-bidder-vaccine.trycloudflare.com/auth/callback",
  "https://marc-operation-bidder-vaccine.trycloudflare.com/auth/shopify/callback",
  "https://marc-operation-bidder-vaccine.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
