# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d6989a96f37a9f08b98c8e6819f9efe"
application_url = "https://heroes-threaded-child-rob.trycloudflare.com"
embedded = true
name = "Quantity-Breaks-Testing"
handle = "quantity-breaks-testing-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "simplebundleapp.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products,read_themes"

[auth]
redirect_urls = [
  "https://heroes-threaded-child-rob.trycloudflare.com/auth/callback",
  "https://heroes-threaded-child-rob.trycloudflare.com/auth/shopify/callback",
  "https://heroes-threaded-child-rob.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://heroes-threaded-child-rob.trycloudflare.com/app/proxy"
subpath = "quantityBreaks"
prefix = "apps"

[pos]
embedded = false
